-- ==============================================================================
-- ADMIN DASHBOARD - NEW TABLES
-- Run this in Supabase SQL Editor to add discount and admin user tables
-- ==============================================================================

-- 1. DISCOUNTS TABLE
CREATE TABLE IF NOT EXISTS public.discounts (
    discount_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE,                              -- Nullable for automatic discounts
    name TEXT NOT NULL,                            -- Discount name/description
    type TEXT NOT NULL CHECK (type IN ('massive', 'individual', 'rule', 'seasonal')),
    discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
    value NUMERIC NOT NULL,                        -- 5 for 5% or 5000 for $5000
    min_order_amount NUMERIC DEFAULT 0,            -- Minimum order for rule-based
    min_quantity INT DEFAULT 0,                    -- Minimum items for rule-based
    user_id BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL,  -- Null for massive/rule
    category_id BIGINT REFERENCES public.product_categories(category_id) ON DELETE SET NULL,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    max_uses INT,                                  -- Max total uses (null = unlimited)
    current_uses INT DEFAULT 0,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS idx_discounts_code ON public.discounts(code);
CREATE INDEX IF NOT EXISTS idx_discounts_type ON public.discounts(type);
CREATE INDEX IF NOT EXISTS idx_discounts_user_id ON public.discounts(user_id);
CREATE INDEX IF NOT EXISTS idx_discounts_active ON public.discounts(active);

-- 2. DISCOUNT USAGE TABLE (to track who used which discount)
CREATE TABLE IF NOT EXISTS public.discount_usage (
    usage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_id BIGINT REFERENCES public.discounts(discount_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL,
    order_id BIGINT REFERENCES public.orders(order_id) ON DELETE SET NULL,
    amount_saved NUMERIC NOT NULL,                 -- How much was saved
    used_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_discount_usage_discount_id ON public.discount_usage(discount_id);
CREATE INDEX IF NOT EXISTS idx_discount_usage_user_id ON public.discount_usage(user_id);

-- 3. ADMIN USERS TABLE
CREATE TABLE IF NOT EXISTS public.admin_users (
    admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'viewer' CHECK (role IN ('super_admin', 'manager', 'viewer')),
    active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for login lookups
CREATE INDEX IF NOT EXISTS idx_admin_users_email ON public.admin_users(email);

-- 4. ACTIVITY LOG TABLE (for audit trail)
CREATE TABLE IF NOT EXISTS public.admin_activity_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES public.admin_users(admin_id) ON DELETE SET NULL,
    action TEXT NOT NULL,                          -- 'login', 'update_order', 'create_discount', etc.
    entity_type TEXT,                              -- 'order', 'discount', 'user', etc.
    entity_id BIGINT,                              -- ID of the affected entity
    details JSONB,                                 -- Additional details
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_activity_log_admin_id ON public.admin_activity_log(admin_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_created_at ON public.admin_activity_log(created_at);

-- 5. ADD DISCOUNT FIELD TO ORDERS (to track applied discounts)
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount_id BIGINT REFERENCES public.discounts(discount_id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount_amount NUMERIC DEFAULT 0;

-- 6. ADD NOTES FIELD TO USERS (for admin notes about customers)
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS admin_notes TEXT;

-- ==============================================================================
-- ROW LEVEL SECURITY
-- ==============================================================================

-- Discounts - viewable by authenticated users
ALTER TABLE public.discounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Discounts are viewable by everyone" ON public.discounts FOR SELECT USING (true);

-- Admin users - only service role can access
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
-- No public policy - only service role key can access

-- Activity log - only service role can access
ALTER TABLE public.admin_activity_log ENABLE ROW LEVEL SECURITY;
-- No public policy - only service role key can access

-- ==============================================================================
-- SAMPLE DATA (Optional - Remove in production)
-- ==============================================================================

-- Create default super admin (password: admin123 - CHANGE IN PRODUCTION!)
-- Note: You'll need to hash the password properly in the application
-- INSERT INTO public.admin_users (email, password_hash, name, role) VALUES
-- ('admin@milhojaldres.com', '$2b$12$xyz...', 'Administrador', 'super_admin');

-- Sample discounts
-- INSERT INTO public.discounts (code, name, type, discount_type, value, active) VALUES
-- ('BIENVENIDO10', 'Descuento de bienvenida', 'massive', 'percentage', 10, true),
-- ('VIP20', 'Descuento VIP', 'individual', 'percentage', 20, true);

-- Sample rule-based discount (orders > 500,000 get 5% off)
-- INSERT INTO public.discounts (name, type, discount_type, value, min_order_amount, active) VALUES
-- ('Compras mayores a 500k', 'rule', 'percentage', 5, 500000, true);
