-- ==============================================================================
-- SCHEMA DE MILHOJALDRES BOT
-- Copia y pega todo este contenido en el Editor SQL de Supabase y ejecútalo.
-- ==============================================================================

-- 1. TABLA DE USUARIOS
create table public.users (
  user_id bigint generated by default as identity primary key,
  telegram_id bigint unique not null,
  nombre text,
  telefono text,
  direccion text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. CATEGORÍAS DE PRODUCTOS
create table public.product_categories (
  category_id bigint generated by default as identity primary key,
  name text not null,
  icon_emoji text not null
);

-- 3. PRODUCTOS
create table public.products (
  product_id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  precio numeric not null,
  categoria text, -- redundante pero útil para lectura rápida
  category_id bigint references public.product_categories(category_id),
  activo boolean default true,
  disponible boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. ÓRDENES
create table public.orders (
  order_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id),
  estado text default 'pending', -- pending, confirmed, preparing, ready, delivered, cancelled
  subtotal numeric default 0,
  tax numeric default 0,
  delivery_fee numeric default 0,
  total numeric not null,
  is_paid boolean default false,
  notas text,
  fecha_orden timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. ITEMS DE ÓRDENES
create table public.order_items (
  item_id bigint generated by default as identity primary key,
  order_id bigint references public.orders(order_id),
  product_id bigint references public.products(product_id),
  cantidad int not null,
  precio_unitario numeric not null,
  subtotal numeric not null
);

-- 6. KNOWLEDGE BASE (Para la IA)
create table public.knowledge_base (
  kb_id bigint generated by default as identity primary key,
  pregunta text not null,
  respuesta text not null,
  palabras_clave text[], -- Array de texto
  veces_usado int default 0,
  confianza numeric default 1.0,
  activa boolean default true
);

-- 7. PREFERENCIAS DE USUARIO
create table public.preferences (
  pref_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id),
  notificaciones boolean default true,
  favoritos bigint[] -- Array de IDs de productos
);

-- ==============================================================================
-- DATOS DE EJEMPLO (SEED DATA)
-- ==============================================================================

-- Categorías
insert into public.product_categories (name, icon_emoji) values
('Milhojas', '🍰'),
('Bebidas', '☕'),
('Postres', '🍮');

-- Productos
insert into public.products (nombre, descripcion, precio, categoria, category_id, activo, disponible) values
('Milhoja Tradicional', 'Nuestra clásica milhoja con arequipe casero y crema.', 5000, 'Milhojas', 1, true, true),
('Milhoja Chantilly', 'Milhoja rellena de suave crema chantilly y fresas.', 6500, 'Milhojas', 1, true, true),
('Milhoja Nutella', 'Crocante milhoja con capas de Nutella original.', 7000, 'Milhojas', 1, true, true),
('Café Americano', 'Café negro recién molido, 9oz.', 3500, 'Bebidas', 2, true, true),
('Capuchino', 'Espresso con leche espumada y cacao.', 4500, 'Bebidas', 2, true, true),
('Cheesecake de Frutos Rojos', 'Porción de cheesecake artesanal.', 8000, 'Postres', 3, true, true);

-- Knowledge Base
insert into public.knowledge_base (pregunta, respuesta, palabras_clave) values
('¿Cuál es el horario?', 'Atendemos de Lunes a Viernes de 8am a 6pm, y Sábados de 9am a 5pm.', ARRAY['horario', 'hora', 'abierto']),
('¿Hacen domicilios?', 'No realizamos domicilios directos. Puedes enviar a tu mensajero de confianza a recoger el pedido.', ARRAY['domicilio', 'envio', 'llevan']),
('¿Dónde están ubicados?', 'Tenemos puntos en Calle 96b #20d-70 y Cra 81b #19b-80.', ARRAY['ubicacion', 'direccion', 'donde']);

-- ==============================================================================
-- ACTIVAR RLS (Row Level Security) - IMPORTANTE
-- Esto permite que cualquiera lea productos, pero solo el dueño vea sus pedidos
-- ==============================================================================

alter table public.products enable row level security;
create policy "Public products are viewable by everyone" on public.products for select using (true);

alter table public.product_categories enable row level security;
create policy "Public categories are viewable by everyone" on public.product_categories for select using (true);

alter table public.knowledge_base enable row level security;
create policy "Public KB is viewable by everyone" on public.knowledge_base for select using (true);

alter table public.users enable row level security;
create policy "Users can insert their own profile" on public.users for insert with check (true);
create policy "Users can view own profile" on public.users for select using (telegram_id::text = current_setting('request.jwt.claim.sub', true)); -- Simplificado para este ejemplo

-- Nota: Para el dashboard admin, usamos la Service Role Key, que se salta estas reglas.
